using System;
using System.Collections.Generic;

namespace NES.Components.CPU
{

    public partial class _6502
    {
       public struct INSTRUCTION
        {
            public string name { get; set; }
            public Func<byte> operate { get; set; }
            public Func<byte> addrMode { get; set; }

            public byte cycles { get; set; }

            public INSTRUCTION(string name, Func<byte> op, Func<byte> addr, byte cycles)
            {
                this.name = name;
                operate = op;
                addrMode = addr;
                this.cycles = cycles;
            }

        }

        public static List<INSTRUCTION> InstructionList; // Matrix of all the cpu instructions

        void BuildInstrtions()
        {
            InstructionList = new List<INSTRUCTION>(){
                new INSTRUCTION( "BRK", BRK, IMM, 7 ),new INSTRUCTION( "ORA", ORA, IZX, 6 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "???", NOP, IMP, 3 ),new INSTRUCTION( "ORA", ORA, ZP0, 3 ),new INSTRUCTION( "ASL", ASL, ZP0, 5 ),new INSTRUCTION( "???", XXX, IMP, 5 ),new INSTRUCTION( "PHP", PHP, IMP, 3 ),new INSTRUCTION( "ORA", ORA, IMM, 2 ),new INSTRUCTION( "ASL", ASL, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "ORA", ORA, ABS, 4 ),new INSTRUCTION( "ASL", ASL, ABS, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),
                new INSTRUCTION( "BPL", BPL, REL, 2 ),new INSTRUCTION( "ORA", ORA, IZY, 5 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "ORA", ORA, ZPX, 4 ),new INSTRUCTION( "ASL", ASL, ZPX, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),new INSTRUCTION( "CLC", CLC, IMP, 2 ),new INSTRUCTION( "ORA", ORA, ABY, 4 ),new INSTRUCTION( "???", NOP, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 7 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "ORA", ORA, ABX, 4 ),new INSTRUCTION( "ASL", ASL, ABX, 7 ),new INSTRUCTION( "???", XXX, IMP, 7 ),
                new INSTRUCTION( "JSR", JSR, ABS, 6 ),new INSTRUCTION( "AND", AND, IZX, 6 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "BIT", BIT, ZP0, 3 ),new INSTRUCTION( "AND", AND, ZP0, 3 ),new INSTRUCTION( "ROL", ROL, ZP0, 5 ),new INSTRUCTION( "???", XXX, IMP, 5 ),new INSTRUCTION( "PLP", PLP, IMP, 4 ),new INSTRUCTION( "AND", AND, IMM, 2 ),new INSTRUCTION( "ROL", ROL, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "BIT", BIT, ABS, 4 ),new INSTRUCTION( "AND", AND, ABS, 4 ),new INSTRUCTION( "ROL", ROL, ABS, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),
                new INSTRUCTION( "BMI", BMI, REL, 2 ),new INSTRUCTION( "AND", AND, IZY, 5 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "AND", AND, ZPX, 4 ),new INSTRUCTION( "ROL", ROL, ZPX, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),new INSTRUCTION( "SEC", SEC, IMP, 2 ),new INSTRUCTION( "AND", AND, ABY, 4 ),new INSTRUCTION( "???", NOP, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 7 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "AND", AND, ABX, 4 ),new INSTRUCTION( "ROL", ROL, ABX, 7 ),new INSTRUCTION( "???", XXX, IMP, 7 ),
                new INSTRUCTION( "RTI", RTI, IMP, 6 ),new INSTRUCTION( "EOR", EOR, IZX, 6 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "???", NOP, IMP, 3 ),new INSTRUCTION( "EOR", EOR, ZP0, 3 ),new INSTRUCTION( "LSR", LSR, ZP0, 5 ),new INSTRUCTION( "???", XXX, IMP, 5 ),new INSTRUCTION( "PHA", PHA, IMP, 3 ),new INSTRUCTION( "EOR", EOR, IMM, 2 ),new INSTRUCTION( "LSR", LSR, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "JMP", JMP, ABS, 3 ),new INSTRUCTION( "EOR", EOR, ABS, 4 ),new INSTRUCTION( "LSR", LSR, ABS, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),
                new INSTRUCTION( "BVC", BVC, REL, 2 ),new INSTRUCTION( "EOR", EOR, IZY, 5 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "EOR", EOR, ZPX, 4 ),new INSTRUCTION( "LSR", LSR, ZPX, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),new INSTRUCTION( "CLI", CLI, IMP, 2 ),new INSTRUCTION( "EOR", EOR, ABY, 4 ),new INSTRUCTION( "???", NOP, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 7 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "EOR", EOR, ABX, 4 ),new INSTRUCTION( "LSR", LSR, ABX, 7 ),new INSTRUCTION( "???", XXX, IMP, 7 ),
                new INSTRUCTION( "RTS", RTS, IMP, 6 ),new INSTRUCTION( "ADC", ADC, IZX, 6 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "???", NOP, IMP, 3 ),new INSTRUCTION( "ADC", ADC, ZP0, 3 ),new INSTRUCTION( "ROR", ROR, ZP0, 5 ),new INSTRUCTION( "???", XXX, IMP, 5 ),new INSTRUCTION( "PLA", PLA, IMP, 4 ),new INSTRUCTION( "ADC", ADC, IMM, 2 ),new INSTRUCTION( "ROR", ROR, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "JMP", JMP, IND, 5 ),new INSTRUCTION( "ADC", ADC, ABS, 4 ),new INSTRUCTION( "ROR", ROR, ABS, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),
                new INSTRUCTION( "BVS", BVS, REL, 2 ),new INSTRUCTION( "ADC", ADC, IZY, 5 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "ADC", ADC, ZPX, 4 ),new INSTRUCTION( "ROR", ROR, ZPX, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),new INSTRUCTION( "SEI", SEI, IMP, 2 ),new INSTRUCTION( "ADC", ADC, ABY, 4 ),new INSTRUCTION( "???", NOP, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 7 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "ADC", ADC, ABX, 4 ),new INSTRUCTION( "ROR", ROR, ABX, 7 ),new INSTRUCTION( "???", XXX, IMP, 7 ),
                new INSTRUCTION( "???", NOP, IMP, 2 ),new INSTRUCTION( "STA", STA, IZX, 6 ),new INSTRUCTION( "???", NOP, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 6 ),new INSTRUCTION( "STY", STY, ZP0, 3 ),new INSTRUCTION( "STA", STA, ZP0, 3 ),new INSTRUCTION( "STX", STX, ZP0, 3 ),new INSTRUCTION( "???", XXX, IMP, 3 ),new INSTRUCTION( "DEY", DEY, IMP, 2 ),new INSTRUCTION( "???", NOP, IMP, 2 ),new INSTRUCTION( "TXA", TXA, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "STY", STY, ABS, 4 ),new INSTRUCTION( "STA", STA, ABS, 4 ),new INSTRUCTION( "STX", STX, ABS, 4 ),new INSTRUCTION( "???", XXX, IMP, 4 ),
                new INSTRUCTION( "BCC", BCC, REL, 2 ),new INSTRUCTION( "STA", STA, IZY, 6 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 6 ),new INSTRUCTION( "STY", STY, ZPX, 4 ),new INSTRUCTION( "STA", STA, ZPX, 4 ),new INSTRUCTION( "STX", STX, ZPY, 4 ),new INSTRUCTION( "???", XXX, IMP, 4 ),new INSTRUCTION( "TYA", TYA, IMP, 2 ),new INSTRUCTION( "STA", STA, ABY, 5 ),new INSTRUCTION( "TXS", TXS, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 5 ),new INSTRUCTION( "???", NOP, IMP, 5 ),new INSTRUCTION( "STA", STA, ABX, 5 ),new INSTRUCTION( "???", XXX, IMP, 5 ),new INSTRUCTION( "???", XXX, IMP, 5 ),
                new INSTRUCTION( "LDY", LDY, IMM, 2 ),new INSTRUCTION( "LDA", LDA, IZX, 6 ),new INSTRUCTION( "LDX", LDX, IMM, 2 ),new INSTRUCTION( "???", XXX, IMP, 6 ),new INSTRUCTION( "LDY", LDY, ZP0, 3 ),new INSTRUCTION( "LDA", LDA, ZP0, 3 ),new INSTRUCTION( "LDX", LDX, ZP0, 3 ),new INSTRUCTION( "???", XXX, IMP, 3 ),new INSTRUCTION( "TAY", TAY, IMP, 2 ),new INSTRUCTION( "LDA", LDA, IMM, 2 ),new INSTRUCTION( "TAX", TAX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "LDY", LDY, ABS, 4 ),new INSTRUCTION( "LDA", LDA, ABS, 4 ),new INSTRUCTION( "LDX", LDX, ABS, 4 ),new INSTRUCTION( "???", XXX, IMP, 4 ),
                new INSTRUCTION( "BCS", BCS, REL, 2 ),new INSTRUCTION( "LDA", LDA, IZY, 5 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 5 ),new INSTRUCTION( "LDY", LDY, ZPX, 4 ),new INSTRUCTION( "LDA", LDA, ZPX, 4 ),new INSTRUCTION( "LDX", LDX, ZPY, 4 ),new INSTRUCTION( "???", XXX, IMP, 4 ),new INSTRUCTION( "CLV", CLV, IMP, 2 ),new INSTRUCTION( "LDA", LDA, ABY, 4 ),new INSTRUCTION( "TSX", TSX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 4 ),new INSTRUCTION( "LDY", LDY, ABX, 4 ),new INSTRUCTION( "LDA", LDA, ABX, 4 ),new INSTRUCTION( "LDX", LDX, ABY, 4 ),new INSTRUCTION( "???", XXX, IMP, 4 ),
                new INSTRUCTION( "CPY", CPY, IMM, 2 ),new INSTRUCTION( "CMP", CMP, IZX, 6 ),new INSTRUCTION( "???", NOP, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "CPY", CPY, ZP0, 3 ),new INSTRUCTION( "CMP", CMP, ZP0, 3 ),new INSTRUCTION( "DEC", DEC, ZP0, 5 ),new INSTRUCTION( "???", XXX, IMP, 5 ),new INSTRUCTION( "INY", INY, IMP, 2 ),new INSTRUCTION( "CMP", CMP, IMM, 2 ),new INSTRUCTION( "DEX", DEX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "CPY", CPY, ABS, 4 ),new INSTRUCTION( "CMP", CMP, ABS, 4 ),new INSTRUCTION( "DEC", DEC, ABS, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),
                new INSTRUCTION( "BNE", BNE, REL, 2 ),new INSTRUCTION( "CMP", CMP, IZY, 5 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "CMP", CMP, ZPX, 4 ),new INSTRUCTION( "DEC", DEC, ZPX, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),new INSTRUCTION( "CLD", CLD, IMP, 2 ),new INSTRUCTION( "CMP", CMP, ABY, 4 ),new INSTRUCTION( "NOP", NOP, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 7 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "CMP", CMP, ABX, 4 ),new INSTRUCTION( "DEC", DEC, ABX, 7 ),new INSTRUCTION( "???", XXX, IMP, 7 ),
                new INSTRUCTION( "CPX", CPX, IMM, 2 ),new INSTRUCTION( "SBC", SBC, IZX, 6 ),new INSTRUCTION( "???", NOP, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "CPX", CPX, ZP0, 3 ),new INSTRUCTION( "SBC", SBC, ZP0, 3 ),new INSTRUCTION( "INC", INC, ZP0, 5 ),new INSTRUCTION( "???", XXX, IMP, 5 ),new INSTRUCTION( "INX", INX, IMP, 2 ),new INSTRUCTION( "SBC", SBC, IMM, 2 ),new INSTRUCTION( "NOP", NOP, IMP, 2 ),new INSTRUCTION( "???", SBC, IMP, 2 ),new INSTRUCTION( "CPX", CPX, ABS, 4 ),new INSTRUCTION( "SBC", SBC, ABS, 4 ),new INSTRUCTION( "INC", INC, ABS, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),
                new INSTRUCTION( "BEQ", BEQ, REL, 2 ),new INSTRUCTION( "SBC", SBC, IZY, 5 ),new INSTRUCTION( "???", XXX, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 8 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "SBC", SBC, ZPX, 4 ),new INSTRUCTION( "INC", INC, ZPX, 6 ),new INSTRUCTION( "???", XXX, IMP, 6 ),new INSTRUCTION( "SED", SED, IMP, 2 ),new INSTRUCTION( "SBC", SBC, ABY, 4 ),new INSTRUCTION( "NOP", NOP, IMP, 2 ),new INSTRUCTION( "???", XXX, IMP, 7 ),new INSTRUCTION( "???", NOP, IMP, 4 ),new INSTRUCTION( "SBC", SBC, ABX, 4 ),new INSTRUCTION( "INC", INC, ABX, 7 ),new INSTRUCTION( "???", XXX, IMP, 7 )
            };
    }

}
}